spring.application.name=bus-booking
spring.config.import=optional:configserver:http://localhost:8888

spring.datasource.url=jdbc:mysql://localhost:3306/reservation-service?createDatabaseIfNotExist=true
server.port=${PORT:8081}

#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.client.service-url.default-zone=http://localhost:8761/eureka/
#eureka.instance.prefer-ip-address=true

#Actuator enpoints for Circuit Breaker
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
 
#Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.bus-booking.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.bus-booking.failureRateThreshold=50
resilience4j.circuitbreaker.instances.Ebus-booking.minimumNumber-of-calls=5
resilience4j.circuitbreaker.instances.bus-booking.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.bus-booking.waitDurationInOpenState=5S
resilience4j.circuitbreaker.instances.bus-booking.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.bus-booking.slidingWindowSize=10
resilience4j.circuitbreaker.instances.bus-booking.slidingWindowType=count-based
#eureka.client.register-with-eureka=true
